kind = "DojoModel"
class_hash = "0x583c7f27c2b6ec25cc6926b2ec436afcc37d93183c3c69e85ab1746c1a0e63e"
original_class_hash = "0x583c7f27c2b6ec25cc6926b2ec436afcc37d93183c3c69e85ab1746c1a0e63e"
abi = "manifests/prod/base/abis/models/jokers_ls_mod-NeonPokerHandEvent-67edbc43.json"
tag = "jokers_ls_mod-NeonPokerHandEvent"
qualified_path = "jokers_ls_mod::models::data::events::neon_poker_hand_event"
manifest_name = "jokers_ls_mod-NeonPokerHandEvent-67edbc43"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "neon_cards_idx"
type = "Array<u32>"
key = false

[[members]]
name = "multi"
type = "u32"
key = false

[[members]]
name = "points"
type = "u32"
key = false
