kind = "DojoModel"
class_hash = "0x399007aacf575adf49227dd511af139ccbaf36c3fdee10210c6add0c714e322"
original_class_hash = "0x399007aacf575adf49227dd511af139ccbaf36c3fdee10210c6add0c714e322"
abi = "manifests/prod/base/abis/models/jokers_ls_mod-Beast-44ab404a.json"
tag = "jokers_ls_mod-Beast"
qualified_path = "jokers_ls_mod::models::data::beast::beast"
manifest_name = "jokers_ls_mod-Beast-44ab404a"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "beast_id"
type = "u32"
key = false

[[members]]
name = "tier"
type = "u8"
key = false

[[members]]
name = "level"
type = "u8"
key = false

[[members]]
name = "health"
type = "u32"
key = false

[[members]]
name = "current_health"
type = "u32"
key = false

[[members]]
name = "attack"
type = "u32"
key = false

[[members]]
name = "type_beast"
type = "TypeBeast"
key = false
