kind = "DojoModel"
class_hash = "0x5c142fae84f2b12147dd0a6d76475c950e9ff010e41a36d5d60e7cff9c127a4"
original_class_hash = "0x5c142fae84f2b12147dd0a6d76475c950e9ff010e41a36d5d60e7cff9c127a4"
abi = "manifests/prod/base/abis/models/jokers_ls_mod-RageRound-5d3cb743.json"
tag = "jokers_ls_mod-RageRound"
qualified_path = "jokers_ls_mod::models::status::game::rage::rage_round"
manifest_name = "jokers_ls_mod-RageRound-5d3cb743"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "is_active"
type = "bool"
key = false

[[members]]
name = "current_probability"
type = "u16"
key = false

[[members]]
name = "active_rage_ids"
type = "Span<u32>"
key = false

[[members]]
name = "last_active_level"
type = "u8"
key = false
