kind = "DojoModel"
class_hash = "0xa0013335c6962212c6e68a1ef5bc8bd11d1af9e1711b5d6b7de339071f9cd8"
original_class_hash = "0xa0013335c6962212c6e68a1ef5bc8bd11d1af9e1711b5d6b7de339071f9cd8"
abi = "manifests/prod/base/abis/models/jokers_ls_mod-ModifierCardSuitEvent-79c4e5cc.json"
tag = "jokers_ls_mod-ModifierCardSuitEvent"
qualified_path = "jokers_ls_mod::models::data::events::modifier_card_suit_event"
manifest_name = "jokers_ls_mod-ModifierCardSuitEvent-79c4e5cc"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u32"
key = false

[[members]]
name = "modifier_card_idx"
type = "u32"
key = false

[[members]]
name = "current_hand_card_idx"
type = "u32"
key = false

[[members]]
name = "suit"
type = "Suit"
key = false
