[world]
description = "jokers of neon"
name = "jokers_ls_mod"
seed = "jokers_ls_mod"

[namespace]
default = "jokers_ls_mod"
mappings = { }

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
# Default account for katana with seed = 0
account_address = ""
private_key = ""
# world_address = "0x7d1b0c56b70f543f40cffb9e120316fc764fcc452e7c1636fee3330d564aa7f"

[migration]
skip_contracts = []
