const AMMIT_BEAST_ID: u32 = 0;
const ANANSI_BEAST_ID: u32 = 1;
const BALROG_BEAST_ID: u32 = 2;
const BANSHEE_BEAST_ID: u32 = 3;
const BASILISK_BEAST_ID: u32 = 4;
const BEAR_BEAST_ID: u32 = 5;
const BEHEMOTH_BEAST_ID: u32 = 6;
const BERSERKER_BEAST_ID: u32 = 7;
const BIGFOOT_BEAST_ID: u32 = 8;
const CHIMERA_BEAST_ID: u32 = 9;
const CHUPACABRA_BEAST_ID: u32 = 10;
const COLOSSUS_BEAST_ID: u32 = 11;
const CYCLOPS_BEAST_ID: u32 = 12;
const DIREWOLF_BEAST_ID: u32 = 13;
const DRAGON_BEAST_ID: u32 = 14;
const DRAUGR_BEAST_ID: u32 = 15;
const ENT_BEAST_ID: u32 = 16;
const ETTIN_BEAST_ID: u32 = 17;
const FAIRY_BEAST_ID: u32 = 18;
const FENRIR_BEAST_ID: u32 = 19;
const GHOUL_BEAST_ID: u32 = 20;
const GIANT_BEAST_ID: u32 = 21;
const GNOME_BEAST_ID: u32 = 22;
const GOBLIN_BEAST_ID: u32 = 23;
const GOLEM_BEAST_ID: u32 = 24;
const GORGON_BEAST_ID: u32 = 25;
const GRIFFIN_BEAST_ID: u32 = 26;
const HARPY_BEAST_ID: u32 = 27;
const HIPPOGRIFF_BEAST_ID: u32 = 28;
const HYDRA_BEAST_ID: u32 = 29;
const JAGUAR_BEAST_ID: u32 = 30;
const JIANGSHI_BEAST_ID: u32 = 31;
const JOTUNN_BEAST_ID: u32 = 32;
const JUGGERNAUT_BEAST_ID: u32 = 33;
const KAPPA_BEAST_ID: u32 = 34;
const KELPIE_BEAST_ID: u32 = 35;
const KITSUNE_BEAST_ID: u32 = 36;
const KRAKEN_BEAST_ID: u32 = 37;
const LEPRECHAUN_BEAST_ID: u32 = 38;
const LEVIATHAN_BEAST_ID: u32 = 39;
const LICH_BEAST_ID: u32 = 40;
const MANTICORE_BEAST_ID: u32 = 41;
const MANTIS_BEAST_ID: u32 = 42;
const MINOTAUR_BEAST_ID: u32 = 43;
const NEMEANLION_BEAST_ID: u32 = 44;
const NEPHILIM_BEAST_ID: u32 = 45;
const NUE_BEAST_ID: u32 = 46;
const OGRE_BEAST_ID: u32 = 47;
const ONI_BEAST_ID: u32 = 48;
const ORC_BEAST_ID: u32 = 49;
const PEGASUS_BEAST_ID: u32 = 50;
const PHOENIX_BEAST_ID: u32 = 51;
const PIXIE_BEAST_ID: u32 = 52;
const QILIN_BEAST_ID: u32 = 53;
const RAKSHASA_BEAST_ID: u32 = 54;
const RAT_BEAST_ID: u32 = 55;
const ROC_BEAST_ID: u32 = 56;
const SATORI_BEAST_ID: u32 = 57;
const SKELETON_BEAST_ID: u32 = 58;
const SKINWALKER_BEAST_ID: u32 = 59;
const SPIDER_BEAST_ID: u32 = 60;
const SPRITE_BEAST_ID: u32 = 61;
const TARRASQUE_BEAST_ID: u32 = 62;
const TITAN_BEAST_ID: u32 = 63;
const TROLL_BEAST_ID: u32 = 64;
const TYPHON_BEAST_ID: u32 = 65;
const VAMPIRE_BEAST_ID: u32 = 66;
const WARLOCK_BEAST_ID: u32 = 67;
const WENDIGO_BEAST_ID: u32 = 68;
const WERETIGER_BEAST_ID: u32 = 69;
const WEREWOLF_BEAST_ID: u32 = 70;
const WOLF_BEAST_ID: u32 = 71;
const WRAITH_BEAST_ID: u32 = 72;
const WYVERN_BEAST_ID: u32 = 73;
const YETI_BEAST_ID: u32 = 74;

fn all_beast() -> Array<u32> {
    array![
        AMMIT_BEAST_ID,
        ANANSI_BEAST_ID,
        BALROG_BEAST_ID,
        BANSHEE_BEAST_ID,
        BASILISK_BEAST_ID,
        BEAR_BEAST_ID,
        BEHEMOTH_BEAST_ID,
        BERSERKER_BEAST_ID,
        BIGFOOT_BEAST_ID,
        CHIMERA_BEAST_ID,
        CHUPACABRA_BEAST_ID,
        COLOSSUS_BEAST_ID,
        CYCLOPS_BEAST_ID,
        DIREWOLF_BEAST_ID,
        DRAGON_BEAST_ID,
        DRAUGR_BEAST_ID,
        ENT_BEAST_ID,
        ETTIN_BEAST_ID,
        FAIRY_BEAST_ID,
        FENRIR_BEAST_ID,
        GHOUL_BEAST_ID,
        GIANT_BEAST_ID,
        GNOME_BEAST_ID,
        GOBLIN_BEAST_ID,
        GOLEM_BEAST_ID,
        GORGON_BEAST_ID,
        GRIFFIN_BEAST_ID,
        HARPY_BEAST_ID,
        HIPPOGRIFF_BEAST_ID,
        HYDRA_BEAST_ID,
        JAGUAR_BEAST_ID,
        JIANGSHI_BEAST_ID,
        JOTUNN_BEAST_ID,
        JUGGERNAUT_BEAST_ID,
        KAPPA_BEAST_ID,
        KELPIE_BEAST_ID,
        KITSUNE_BEAST_ID,
        KRAKEN_BEAST_ID,
        LEPRECHAUN_BEAST_ID,
        LEVIATHAN_BEAST_ID,
        LICH_BEAST_ID,
        MANTICORE_BEAST_ID,
        MANTIS_BEAST_ID,
        MINOTAUR_BEAST_ID,
        NEMEANLION_BEAST_ID,
        NEPHILIM_BEAST_ID,
        NUE_BEAST_ID,
        OGRE_BEAST_ID,
        ONI_BEAST_ID,
        ORC_BEAST_ID,
        PEGASUS_BEAST_ID,
        PHOENIX_BEAST_ID,
        PIXIE_BEAST_ID,
        QILIN_BEAST_ID,
        RAKSHASA_BEAST_ID,
        RAT_BEAST_ID,
        ROC_BEAST_ID,
        SATORI_BEAST_ID,
        SKELETON_BEAST_ID,
        SKINWALKER_BEAST_ID,
        SPIDER_BEAST_ID,
        SPRITE_BEAST_ID,
        TARRASQUE_BEAST_ID,
        TITAN_BEAST_ID,
        TROLL_BEAST_ID,
        TYPHON_BEAST_ID,
        VAMPIRE_BEAST_ID,
        WARLOCK_BEAST_ID,
        WENDIGO_BEAST_ID,
        WERETIGER_BEAST_ID,
        WEREWOLF_BEAST_ID,
        WOLF_BEAST_ID,
        WRAITH_BEAST_ID,
        WYVERN_BEAST_ID,
        YETI_BEAST_ID
    ]
}

fn is_loot_survivor_beast(beast_id: u32) -> bool {
    beast_id <= YETI_BEAST_ID
}
