const CHALLENGE_ROYAL_FLUSH: u32 = 1;
const CHALLENGE_STRAIGHT_FLUSH: u32 = 2;
const CHALLENGE_FIVE_OF_A_KIND: u32 = 3;
const CHALLENGE_FOUR_OF_A_KIND: u32 = 4;
const CHALLENGE_FULL_HOUSE: u32 = 5;
const CHALLENGE_FLUSH: u32 = 6;
const CHALLENGE_STRAIGHT: u32 = 7;
const CHALLENGE_THREE_OF_A_KIND: u32 = 8;
const CHALLENGE_DOUBLE_PAIR: u32 = 9;
const CHALLENGE_PAIR: u32 = 10;
const CHALLENGE_HIGH_CARD: u32 = 11;

const CHALLENGE_HEARTS: u32 = 12;
const CHALLENGE_CLUBS: u32 = 13;
const CHALLENGE_DIAMONDS: u32 = 14;
const CHALLENGE_SPADES: u32 = 15;

const CHALLENGE_ONE: u32 = 16;
const CHALLENGE_TWO: u32 = 17;
const CHALLENGE_THREE: u32 = 18;
const CHALLENGE_FOUR: u32 = 19;
const CHALLENGE_FIVE: u32 = 20;
const CHALLENGE_SIX: u32 = 21;
const CHALLENGE_SEVEN: u32 = 22;
const CHALLENGE_EIGHT: u32 = 23;
const CHALLENGE_NINE: u32 = 24;
const CHALLENGE_TEN: u32 = 25;
const CHALLENGE_JACK: u32 = 26;
const CHALLENGE_QUEEN: u32 = 27;
const CHALLENGE_KING: u32 = 28;
const CHALLENGE_ACE: u32 = 29;

const CHALLENGE_JOKER: u32 = 30;


fn challenges_all() -> Array<u32> {
    array![
        CHALLENGE_ROYAL_FLUSH,
        CHALLENGE_STRAIGHT_FLUSH,
        CHALLENGE_FIVE_OF_A_KIND,
        CHALLENGE_FOUR_OF_A_KIND,
        CHALLENGE_FULL_HOUSE,
        CHALLENGE_FLUSH,
        CHALLENGE_STRAIGHT,
        CHALLENGE_THREE_OF_A_KIND,
        CHALLENGE_DOUBLE_PAIR,
        CHALLENGE_PAIR,
        CHALLENGE_HIGH_CARD,
        CHALLENGE_HEARTS,
        CHALLENGE_CLUBS,
        CHALLENGE_DIAMONDS,
        CHALLENGE_SPADES,
        CHALLENGE_ONE,
        CHALLENGE_TWO,
        CHALLENGE_THREE,
        CHALLENGE_FOUR,
        CHALLENGE_FIVE,
        CHALLENGE_SIX,
        CHALLENGE_SEVEN,
        CHALLENGE_EIGHT,
        CHALLENGE_NINE,
        CHALLENGE_TEN,
        CHALLENGE_JACK,
        CHALLENGE_QUEEN,
        CHALLENGE_KING,
        CHALLENGE_ACE,
        CHALLENGE_JOKER
    ]
}
